### ISSUE TITLE
strange things in the code...

### ISSUE THREAD

**Issue by marcorra** [joelrich/citojs#10]
Hi

Your **insertNodeHTML()** are only for Triden browsers it seems. 

So look at the function  **createNode()** - line 192. Here you do a return if Triden browsers.

Still - in the same function - you are checking against a Trident browser. Even after you returned.

Further....  **createNodeHTML()** are only linked to from the function **insertNodeHTML()**.

As I mentioned the **insertNodeHTML()** are only for Trident browsers.

Then again inside the **createNodeHTML()** function, you are escaping HTML.

So here you actually looking for Webkit, Firefox and other browsers, inside a function that are only accessible with a Trident browsers.

Can you explain this to me?

**Comment by joelrich** [comment]
The reason for this is that I tried to find the most performant way to initialise the DOM in all browsers. In Internet Explorer up to version 11, it's fastest to use innerHTML which is the reason for the first isTrident check. However, if you don't want to use innerHTML, then it's still much faster to append first a node to the parent before adding content to the node itself. At the moment, the second and third isTrident check is not needed, but it also does not hurt. It is still there to easily compare the different execution paths. The checks for the other browser is just there because I wanted to see how innerHTML performs for them. At some point, they will be removed.

**Comment by aMarCruz** [comment]
Yet, browser detection is evil.

**Comment by joelrich** [comment]
I would not use user agent sniffing to determine whether or not a certain feature can be used. However, in this case, I have to choose between different implementations with different performance characteristics. I could use some kind feature detection to conclude which browser it is, but since I won't use the checked feature what's the difference anyway? Theoretically, I could run a quick benchmark when the page is first accessed, but that will slow down the initial rendering and is overkill. Please let me know if you have a better idea.

**Comment by aMarCruz** [comment]
I think sometimes, BD is the unique option. I use it in [my requestAnimationFrame polyfill](https://gist.github.com/aMarCruz/061f9cced1e5c0855bb7), but is directing very specific bug.
userAgent is easy to hack, even for final users... and there are **too much** variations. My Maxthon browser supports html5 (and have webkit) as Chrome 41, but its userAgent says Chrome 30!

For engine-driven code, I think you must use engine detection, then feature detection, last BD.
In <=IE9, conditional comments o @jscript_version is ok (no uglify friendly). There are only 3 to care about... browsers I don't know.

And I can't post code for this, sorry.

**Comment by aMarCruz** [comment]
Here is an example, from my own PR/patch to cito escapeContent function...
If my library, I had written this:
```javascript
  var escapeContent;
  try {
    // FF throws here, can avoid try testing for helperDiv.innerText
    helperDiv.innerText = '<';
    if (helperDiv.innerHTML === '&lt;') {
      escapeContent = function _escapeContent(value) {
        helperDiv.innerText = '' + value;
        return helperDiv.innerHTML;
      }
    }
  } catch() {};

  escapeContent || (escapeContent = function _escapeContent(value) {
    // replace with functions is ES3 compatible (ie6+)
    return ('' + value).replace(/[&<>]/g, function(ch){
      return ch === '&' ? '&amp;' : ch === '<' ? '&lt;' : '&gt;';
    });
  });
```
ok, this is more verbose, but efficient at runtime, and not BD depedent.
I could not study your code in depth, but I remember this function.

**Comment by joelrich** [comment]
@aMarCruz, in Safari it's faster to create a new escaping element instead of reusing one while in Chrome it is the other way around. How would you use different implementations in this case?

For Trident it makes sense to use feature detection, but for the other engines/browsers I still think it's better to use user agent sniffing as long as all implementations run in all browsers. I mean this is not about checking whether a feature can be used, but using the fastest possible implementation.

**Comment by aMarCruz** [comment]
ok, I got it.
still..., performance varies between versions of the same engine.
In any case, I think is better look for something unique like (documentMode)[http://www.w3schools.com/jsref/prop_doc_documentmode.asp] in IE, and similar things that I know exist in other engines. For wide-scope apps, I don't trust in the userAgent string.

**Comment by aMarCruz** [comment]
I began with dBase III many year ago, then learn HTML in 98, my first web app was an ERP in html/js and something like ajax before Ajax.
I was an C/assembler programmer too, fan of Michael Abrash, and like you, I like performance.

But, the Abrash excellent code for 8086 was not good for 286, and so for 386, 486, Pentium, AMD...
The best-performance-practices for web two year ago (eg.YUI), are really bad things today.
And there are many changes in the js language too.
Eg. think about this micro-op:
```javascript
for (var i=0, len=arr.length; ++i < len;) {...}
```
This is faster in one or two new engines:
```javascript
for (var i = 0; i < arr.length; i++) {...}
```
From my point of view, it's time to find a balance.

I mean, in all this years performance definition has changed, the only constant requirement is compatibility.

We need a new framework/library of decoupled pieces for massive offline first applications, with good performance and lightweight code, mobile friendly. I think vdom is a key piece, and projects as cito is the way.

Thanks for given us your hard work.

**Comment by joelrich** [comment]
While implementing Cito, I have learned a lot about JavaScript/DOM performance, but probably I have been a little bit too extreme in some regards. Now that I am working on a rewrite, I try to find a better balance which should also include less ugly code and nicer APIs. It will likely perform a little bit slower in the vdom-benchmark, but better in more real use cases.

**Comment by jails** [comment]
Over the years I think about the code first and then about optimisations (and only when it doesn't affect the clarity of the code itself). But it's my personnal position.

By the way I reproduced some [live benchmark](http://rawgit.com/crysalead-js/dom-layer/master/examples/speedtest/speedtest.html) to see some of them in action, for what it is worth.

**Comment by aMarCruz** [comment]
wow, wow, wow ...many surprises!!!
I test and re-test this.
Win7, 32bits, Pentium core 3Ghz, 4GB ram
Average ms per loop (run at full screen, rounded, stopped at 200 iterations)

Framework   |Chrome41|Maxthon4| IE11 |Firefox37
------------|----------|--------|------|-------
DomLayer    |   119  |   143  |  378 |  574
Bobril      |  **32**  |   138  |  332 |  388
Cito        |  108   |   139  |  339 |  487
Mithril     |  162   |   167  |  431 |  476
React       |  243   |   339  |  618 |  620
Virtual Dom |  128   |   151  |  428 |  517
------------|----------|--------|------|-------
Backbone    |  156   |   206  |  474  |  240
Ember       |   **96**   |   123  |  387  |  399
Vue         |  140   |   152  |  360  |  620
Vanilla JS  |  131   |   154  |  354  |  223

**Comment by trueadm** [comment]
The animation benchmark will always be advantageous to frameworks that use request animation frame. So those results are not surprising, especially if you've updated Ember to now use Glimmer.

**Comment by aMarCruz** [comment]
Yeah, but backbone _is not using rAF_
Firefix poor performance surprised me.
Ember vs Vue too.
Here with avgs:

Framework   |Chrome41|Maxthon4| IE11 |Firefox37| avg
----------------|--------|--------|------|---------|-------
DomLayer    |   119  |   143  |  378 |  574    | 303.5
Bobril      |  **32**  |   138  |  332 |  388  | 222.5
Cito        |  108   |   139  |  339 |  487    | 268.3
Mithril     |  162   |   167  |  431 |  476    | 309.0
React       |  243   |   339  |  618 |  620    | 455.0
Virtual Dom |  128   |   151  |  428 |  517    | 306.0
----------------|--------|--------|------|---------|-------
Backbone    |  156   |   206  |  474  |  240   | 269.0
Ember       |   96   |   123  |  387  |  399   | 251.3
Vue         |  140   |   152  |  360  |  620   | 318.0
Vanilla JS  |  131   |   154  |  354  |  223   | 215.5
----------------|--------|--------|------|---------|-------
Average     |  131.5 |  171.2 | 410.1 | 454.4

**Comment by trueadm** [comment]
Backbone has a very similar implementation to Vanilla JS, that's why. The Vanilla JS is an awful implementation anyway; no one would hopefully ever code a solution like that for a benchmark!

**Comment by aMarCruz** [comment]
You are right, however, I was surprised.
I still have working applications with vanilla js.

**Comment by jails** [comment]
@aMarCruz interesting summary :+1: ! The battle between Ember vs Vue is not really fair since for Vue.js I used some "advanced template directive" like `v-repeat`, but I'm pretty sure Ember + HTMLBars could provide the same "advanced features", however I only tweeked the initial implementation since I don't know Ember that much.

The issue behind request animation frame is the rendering is asynchoneously delegating to this function, so it can't be benchmarked which explain Bobril's "fake" results (and since the Bobril's `update()` function is not exposed I didn't find any alternative).

@trueadm It was the first implementation which come to my mind in "pure vanilla", but if you have a better implementation in mind for a benchmark, don't hesitate to share your thought.

**Comment by joelrich** [comment]
@jails Why don't you use requestAnimationFrame for all libraries?
For vanilla JS you should use the DOM API for updates. This should improve the performance a lot.

@aMarCruz Here another benchmark with quite different results:
t7+cito: http://t7js.com/dbmonster/precompiled.html
Ember+glimmer: https://dbmonster.firebaseapp.com/
React: http://run.plnkr.co/plunks/Wwgjjpl9NHMO5Nd1TUyN/

**Comment by jails** [comment]
@joelrich requestAnimationFrame will cap the speed to not exceed the display refresh rate which will interfere with the benchmark. But maybe it could work with more circles so it can become negligible.

**Comment by joelrich** [comment]
@jails If the rendering takes less than 16 milliseconds, then you are right.
I have just realised why Bobril's performance seems to be so much better. When invalidate() is called, it does not rerender, but schedules a rerendering for the next animation frame. If invalidate is now called twice before the requestAnimationFrame callback is called, then it seems to be twice as fast. That's probably what you have already meant before. If you enable the FPS meter, then you see that the refresh rate is actually less than in Cito. Nevertheless, that's a pretty interesting technique.

**Comment by aMarCruz** [comment]
@jails you're right, and it is very efficient in mobiles.

**Comment by trueadm** [comment]
Not only is it very efficient in mobiles, it's very efficient in general. It's essentially how game engines work.
