### ISSUE TITLE
Serverside Rendering?

### ISSUE THREAD

**Issue by Citrullin** [joelrich/citojs#30]
Is it possible to use citojs for server-side rendering? Especially needed for SEO.

**Comment by joelrich** [comment]
It does not. I would also recommend to use another library since it isn't actively developed anymore.

If you want to use it anyway, it would be pretty easy to add basic server-side rendering support. For an Internet Explorer performance optimisation, I once implemented some code which uses innerHTML for the initial rendering. This code could also be used on the server - at least with some modifications.

HTML rendering: https://github.com/joelrich/citojs/blob/master/src/vdom.js#L345
Virtual DOM upgrade: https://github.com/joelrich/citojs/blob/master/src/vdom.js#L426

I don't know how it behaves if the virtual dom on the server for the initial HTML rendering does not match the virtual dom in the browser.

By the way, server-side pre-rendering is not that important for SEO anymore. Google runs your JavaScript anyway.

**Comment by Citrullin** [comment]
Ahh okay, they dropped the recommendation in the last year.
